language: objective-c
osx_image: xcode9.4
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - pod lib lint
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
    on_success: change
    on_failure: always
